import numpy as np


def height(x: float, y: float):
    """Returns terrain height (Z) at given 2D coordinate (X, Y)"""
    # Generated by an abstract mathematical function for testing purposes; 
    # Replace with interpolated height matrix in order to simulate real slope

    return (np.sin(x)-2*x)/10 + np.sin(x/10)